<Project>
  <PropertyGroup>
    <IsAotCompatible Condition="'$(IsAotCompatible)' == '' and $([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))">true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup Condition="'$(CLSCompliant)' != ''">
    <AssemblyAttribute Include="System.CLSCompliantAttribute">
      <_Parameter1>$(CLSCompliant)</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <PropertyGroup Condition="'$(RestorePackagesWithLockFile)' == 'true' and '$(ContinuousIntegrationBuild)' == 'true'">
    <RestoreLockedMode>true</RestoreLockedMode>
  </PropertyGroup>

  <PropertyGroup Condition="'$(IsRoslynComponent)' == 'true'">
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <DevelopmentDependency>true</DevelopmentDependency>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
  </PropertyGroup>

  <PropertyGroup Condition="'$(IsPackable)' == 'true'">
    <Copyright>Copyright (c) 2026 aetos</Copyright>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>BSD-2-Clause-Patent</PackageLicenseExpression>
    <Authors>aetos</Authors>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <PackageProjectUrl>https://github.com/aetos382/RoslynTesting</PackageProjectUrl>
    <IncludeSymbols Condition="'$(IncludeSymbols)' == ''">true</IncludeSymbols>
  </PropertyGroup>

  <PropertyGroup Condition="'$(IncludeSymbols)' == 'true'">
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
  </PropertyGroup>

  <ItemGroup Condition="'$(IsPackable)' == 'true'">
    <None Include="$(MSBuildThisFileDirectory)README.md">
      <Pack>true</Pack>
      <PackagePath>/</PackagePath>
      <Visible>false</Visible>
    </None>
  </ItemGroup>

</Project>
